apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: foundationdbclusters.apps.foundationdb.org
spec:
  group: apps.foundationdb.org
  names:
    kind: FoundationDBCluster
    plural: foundationdbclusters
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            configured:
              type: boolean
            connectionString:
              type: string
            containers:
              items:
                type: object
              type: array
            customParameters:
              items:
                type: string
              type: array
            enableTls:
              type: boolean
            env:
              items:
                type: object
              type: array
            faultDomain:
              properties:
                key:
                  type: string
                value:
                  type: string
                valueFrom:
                  type: string
                zoneCount:
                  format: int64
                  type: integer
                zoneIndex:
                  format: int64
                  type: integer
              type: object
            initContainers:
              items:
                type: object
              type: array
            logGroup:
              type: string
            nextInstanceID:
              format: int64
              type: integer
            peerVerificationRules:
              items:
                type: string
              type: array
            pendingRemovals:
              type: object
            processCounts:
              properties:
                log:
                  format: int64
                  type: integer
                master:
                  format: int64
                  type: integer
                proxy:
                  format: int64
                  type: integer
                resolution:
                  format: int64
                  type: integer
                resolver:
                  format: int64
                  type: integer
                router:
                  format: int64
                  type: integer
                stateless:
                  format: int64
                  type: integer
                storage:
                  format: int64
                  type: integer
                transaction:
                  format: int64
                  type: integer
                unset:
                  format: int64
                  type: integer
              type: object
            replicationMode:
              type: string
            resources:
              type: object
            roleCounts:
              properties:
                logs:
                  format: int64
                  type: integer
                proxies:
                  format: int64
                  type: integer
                resolvers:
                  format: int64
                  type: integer
                storage:
                  format: int64
                  type: integer
              type: object
            runningVersion:
              type: string
            storageClass:
              type: string
            storageEngine:
              type: string
            trustedCAs:
              items:
                type: string
              type: array
            version:
              type: string
            volumeMounts:
              items:
                type: object
              type: array
            volumeSize:
              type: string
            volumes:
              items:
                type: object
              type: array
          required:
          - version
          - volumeSize
          type: object
        status:
          properties:
            fullyReconciled:
              type: boolean
            incorrectProcesses:
              type: object
            missingProcesses:
              type: object
            processCounts:
              properties:
                log:
                  format: int64
                  type: integer
                master:
                  format: int64
                  type: integer
                proxy:
                  format: int64
                  type: integer
                resolution:
                  format: int64
                  type: integer
                resolver:
                  format: int64
                  type: integer
                router:
                  format: int64
                  type: integer
                stateless:
                  format: int64
                  type: integer
                storage:
                  format: int64
                  type: integer
                transaction:
                  format: int64
                  type: integer
                unset:
                  format: int64
                  type: integer
              type: object
          required:
          - fullyReconciled
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
