apiVersion: v1
kind: ServiceAccount
metadata:
  name: fdb-kubernetes-operator-controller-manager
  labels:
    {{- include "chart.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: {{ .Values.operator.name }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 4059
        runAsGroup: 4059
        fsGroup: 4059
      volumes:
      - name: tmp
        emptyDir: {}
      - name: logs
        emptyDir: {}
      - name: fdb-binaries
        emptyDir: {}
      initContainers:
        - name: foundationdb-kubernetes-init-6-1
          image: foundationdb/foundationdb-kubernetes-sidecar:6.1.13-1
          args:
            - "--copy-library"
            - "6.1"
            - "--copy-binary"
            - "fdbcli"
            - "--copy-binary"
            - "fdbbackup"
            - "--copy-binary"
            - "fdbrestore"
            - "--output-dir"
            - "/var/output-files/6.1.12"
            - "--init-mode"
          volumeMounts:
            - name: fdb-binaries
              mountPath: /var/output-files
        - name: foundationdb-kubernetes-init-6-2
          image: foundationdb/foundationdb-kubernetes-sidecar:6.2.30-1
          args:
            - "--copy-library"
            - "6.2"
            - "--copy-binary"
            - "fdbcli"
            - "--copy-binary"
            - "fdbbackup"
            - "--copy-binary"
            - "fdbrestore"
            - "--output-dir"
            - "/var/output-files/6.2.30"
            - "--init-mode"
          volumeMounts:
            - name: fdb-binaries
              mountPath: /var/output-files
        - name: foundationdb-kubernetes-init-6-3
          image: foundationdb/foundationdb-kubernetes-sidecar:6.3.10-1
          args:
            - "--copy-library"
            - "6.3"
            - "--copy-binary"
            - "fdbcli"
            - "--copy-binary"
            - "fdbbackup"
            - "--copy-binary"
            - "fdbrestore"
            - "--output-dir"
            - "/var/output-files/6.3.10"
            - "--init-mode"
          volumeMounts:
            - name: fdb-binaries
              mountPath: /var/output-files
      containers:
      - command:
        - /manager
        env:
        - name: FDB_NETWORK_OPTION_EXTERNAL_CLIENT_DIRECTORY
          value: /usr/bin/fdb
        {{- if not .Values.operator.globalMode.enabled }}
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- end }}
        image: {{ .Values.operator.image }}:{{ .Values.operator.tag }}
        name: manager
        ports:
        - containerPort: 8080
          name: metrics
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: logs
          mountPath: /var/log/fdb
        - name: fdb-binaries
          mountPath: /usr/bin/fdb
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 256Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          privileged: false
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics            
        resources:
          {{- toYaml .Values.resources | nindent 12 }}     
      serviceAccountName: fdb-kubernetes-operator-controller-manager
      terminationGracePeriodSeconds: 10
