apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: {{ .Values.operator.rolebinding }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.operator.role }}
subjects:
- kind: ServiceAccount
  name: default