apiVersion: apps.foundationdb.org/v1beta1
kind: FoundationDBCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: foundationdbcluster-sample
spec:
  version: 6.0.18
  replicationMode: double
  volumeSize: "0"
  faultDomain:
    key: foundationdb.org/none
  processCounts:
    stateless: -1
    transaction: -1
  resources:
    requests:
      cpu: 250m
      memory: 128Mi