# This file provides an example of a cluster with a backup running.
#
# The backup resource will bring up backup agents and start a backup. Once it
# is reconciled, you can run backup commands from the backup agent containers:
#
#     # Check Status
#     kubectl exec deployment/sample-cluster-backup-agents -- fdbbackup status
#
#     # List Backups
#     kubectl exec deployment/sample-cluster-backup-agents -- fdbbackup list -b "blobstore://minio@minio-service:9000?bucket=fdb-backups"
#
# This example uses configuration for a local MinIO instance, which is set up as
# part of the local testing environment for the operator. This instance has
# certificates stored in Kubernetes secrets, and credentials that are hardcoded
# in the YAML. This configuration is for testing purposes only. You will need to
# determine the appropriate way of managing certificates and credentials for
# your real environment and endpoints, as well as the appropriate backup
# solution to use. We use MinIO in our local tests due to its lightweight setup,
# but you can backup to any S3-compatible object storage service.
#
# If you are testing this in Docker Desktop, you can browse the local MinIO
# instance at https://localhost:9000. Note: This will use a certificate that
# is not in your browser's trust store, so you will get a security warning.
#
# If you want to test a restore, you can take the following steps:
#
# 1. Apply this YAML file.
# 2. Wait for all resources to be reconciled.
# 3. Set a test key.
# 4. Confirm through `fdbbackup status` that the backup is up-to-date. You can
#    do this by checking the current time and then waiting for the "Last
#    complete log version and timestamp" to be after that time
# 5. Uncomment the line in the backup spec that says `backupState:Stopped` and
#    apply the YAML again.
# 6. Wait for all resources to be reconciled.
# 7. Confirm through `fdbbackup status` that the backup has been stopped.
# 9. Open a CLI and run `writemode on; clearrange '' \xff`.
# 9. Confirm in the CLI that the test key is cleared.
# 10. Uncomment the FoundationDBRestore section below and apply the YAML again.
# 11. Wait for all resources to be reconciled.
# 12. Open a CLI and check the test key.
#
# Once that is done, you can clean up the backup by running:
#     kubectl exec deployment/sample-cluster-backup-agents -- fdbbackup delete -d "blobstore://minio@minio-service:9000/sample-cluster?bucket=fdb-backups"
#
apiVersion: apps.foundationdb.org/v1beta1
kind: FoundationDBCluster
metadata:
  name: sample-cluster
spec:
  version: 6.2.30
  faultDomain:
    key: foundationdb.org/none
  processCounts:
    stateless: -1
  services:
    headless: true
  processes:
    general:
      customParameters:
        - "knob_disable_posix_kernel_aio=1"
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: "16G"
      podTemplate:
        spec:
          securityContext:
            fsGroup: 0
          containers:
            - name: foundationdb
              securityContext:
                runAsUser: 0
              resources:
                requests:
                  cpu: 250m
                  memory: 128Mi
            - name: foundationdb-kubernetes-sidecar
              resources:
                requests:
                  cpu: 250m
                  memory: 128Mi
              securityContext:
                runAsUser: 0
          initContainers:
            - name: foundationdb-kubernetes-init
              resources:
                requests:
                  cpu: 250m
                  memory: 128Mi
              securityContext:
                runAsUser: 0
---
apiVersion: apps.foundationdb.org/v1beta1
kind: FoundationDBBackup
metadata:
  name: sample-cluster
spec:
  version: 6.2.20
  clusterName: sample-cluster
  accountName: minio@minio-service:9000
  #backupState: Stopped
  snapshotPeriodSeconds: 3600
  podTemplateSpec:
    spec:
      containers:
        - name: foundationdb
          env:
            - name: FDB_BLOB_CREDENTIALS
              value: /var/backup-credentials/credentials
            - name: FDB_TLS_CERTIFICATE_FILE
              value: /tmp/fdb-certs/tls.crt
            - name: FDB_TLS_CA_FILE
              value: /tmp/fdb-certs/tls.crt
            - name: FDB_TLS_KEY_FILE
              value: /tmp/fdb-certs/tls.key
          volumeMounts:
            - name: fdb-certs
              mountPath: /tmp/fdb-certs
            - name: backup-credentials
              mountPath: /var/backup-credentials
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 128Mi
          securityContext:
            runAsGroup: 0
            runAsUser: 0
      initContainers:
        - name: foundationdb-kubernetes-init
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            runAsUser: 0
      volumes:
        - name: backup-credentials
          secret:
            secretName: minio-credentials
        - name: fdb-certs
          secret:
            secretName: fdb-kubernetes-operator-secrets
---
#apiVersion: apps.foundationdb.org/v1beta1
#kind: FoundationDBRestore
#metadata:
#  name: sample-cluster
#spec:
#  destinationClusterName: sample-cluster
#  backupURL: "blobstore://minio@minio-service:9000/sample-cluster?bucket=fdb-backups"
