---
apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
type: Opaque
stringData:
    credentials: |
        {
            "accounts": {
                "minio@minio-service": {
                    "secret" : "minio123"
                }
            }
        }
