apiVersion: miniocontroller.min.io/v1beta1
kind: MinIOInstance
metadata:
  name: minio
spec:
  replicas: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
  liveness:
    initialDelaySeconds: 10
    httpGet:
      scheme: HTTPS
  readiness:
    initialDelaySeconds: 10
    httpGet:
      scheme: HTTPS
  externalCertSecret:
    name: fdb-kubernetes-operator-secrets
    type: kubernetes.io/tls