apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    control-plane: controller-manager
    app: fdb-kubernetes-operator-controller-manager
spec:
  selector:
    matchLabels:
      app: fdb-kubernetes-operator-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app: fdb-kubernetes-operator-controller-manager
    spec:
      serviceAccountName: fdb-kubernetes-operator-controller-manager
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: foundationdb/fdb-kubernetes-operator:0.21.1
        name: manager
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 256Mi
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager